### ISSUE TITLE
Help understanding source.conf.

### ISSUE THREAD

**Issue by decimal1969** [kubiko/opengrok-snap#6]
I created an initial file
```
/var/snap/opengrok/common/source.conf
```

with these contents.
```
check_opengrok_config "Dwayne McConnell" "dwayne@us.ibm.com"
```

And ran this command with these results.
```
# opengrok.update-source 
checking if we have 'update-source' script provided by other snap to use
Sourcing '/snap/opengrok/1511/src-updater/update-source'
Running it .....
jq: error (at <stdin>:1): null (null) has no keys
error: error running snapctl: invalid option name: ""
WARNING: Source definition for "" in snap config is missing type or project name
Waiting for 0 tasks to complete....

All code is synced, refresh index
all source synced
```

I'm wondering what I am missing. Based on my previous issue I did run this command.
```
snap connect opengrok:ssh-keys
```

Here are my opengrok connections.
```
# snap connections opengrok
Interface        Plug                      Slot                   Notes
content          -                         opengrok:source-share  -
content          -                         opengrok:tools         -
content          opengrok:data-location    -                      -
content          opengrok:source-location  -                      -
content          opengrok:src-updater      -                      -
home             opengrok:home             :home                  -
mount-observe    opengrok:mount-observe    :mount-observe         manual
network-bind     opengrok:network-bind     :network-bind          -
process-control  opengrok:process-control  :process-control       manual
removable-media  opengrok:removable-media  -                      -
ssh-keys         opengrok:ssh-keys         :ssh-keys              manual
system-observe   opengrok:system-observe   :system-observe        manual
```

**Comment by kubiko** [comment]
I have deprecated the original way to modify `/var/snap/opengrok/common/source.conf` directly.
Instead, I use now `snap set ....`
so for your use case, you need something like:
`$ snap set opengrok sources.opengrok='{"name":"opengrok", "type":"git", "url":"https://github.com/oracle/opengrok.git", "branch":"master"}'`
If you are trying to just sync code from git repos you do not need to have configured git (option there is a relic from the past). You need this only when you want to make git commits.
To error you see, I assume:
`jq` error is because you have not defined any source, so `jq` is trying to parse an empty string (I can probably make it fail more gracefully). So you need to configure the source step as an example above.

If your repos require ssh keys to authenticate, this is a bit tricky. Since all the snap services run as root, by connecting `:ssh-keys` interface, you actually gave opengrok service access to `/root/.ssh/` keys.  So you need to copy all the required ssh keys and ssh config to `/root/.ssh` while maintaining `root` as owner. It's not ideal, but for the multi-user system, this is probably easiest, otherwise, each deployment would need to set which user to run the indexer as.

**Comment by decimal1969** [comment]
I'll go ahead and close. I have not gotten back around to looking at this.
