### ISSUE TITLE
Is is possible to have opengrok-snap point to a src directory outside of the snap?

### ISSUE THREAD

**Issue by decimal1969** [kubiko/opengrok-snap#7]
Suppose I want my source to be located somewhere other than
'''
/var/snap/opengrok/common/src
'''

Is there a way to set the directory to
'''
/home/user/src
'''
instead?

I was thinking there are two parts to the issue.
1. Telling OpenGrok to look in /home/user/src.
2. Giving the snap access to /home/user/src, perhaps with a connection.

**Comment by kubiko** [comment]
This is possible.
you can configure  `opengrok.src-root, ( and `opengrok.src-data` for index data ) with `snap set`. For this case of course confinement is your limitation, and since the index service runs as root, it will not have access to you /home/<***>/ unfortunately.
Mind even if that is resolved, it will still at some point mix git repo file owner, when it runs regular git pull and reindex, it will run `git pull` as root.... Unless you disable auto-index-update, but then you are not getting most of this all in one box solution...
I'm happy to consider this use case and require home-all connections, which you would need to manually connect, probably not a problem here.
If a different location is on the external storage, then this is also covered by the interface.
I assume you want to point it to your home for the reason of disk space-saving, but opengrok is really designed to run more as the server where this is less of a concern.

If this is because you have multiple partitions, e.g. root and home. Then the easiest "cheat" is to update your `/etc/fstab` and bind mount your `/home/user/src` to `/var/snap/opengrok/common/src`.

Then there is one more option, which will sidestep those problems, or more, delegate this problem to "provider snap"
You can construct a custom "empty" snap with two slots which will provide access to your desired location, and at which point you resolve needed permissions on the provider side. A bit more complicated though...

**Comment by decimal1969** [comment]
Thanks for confirming. I guess the reason I want to do this is because I'm not sure if the current OpenGrok <-> git connection does what I need. For my product we have many repos which share branch names so I want my OpenGrok projects to be based on the branch name and the top level directory under the branch name to be the repo name.

So if I have `branch1` and `branch2` and `repoA` and `repoB`, I want my my OpenGrok URL for `fileX` from `repoA` on `branch1` to be `http://{hostname}:8080/source/branch1/repoA/fileX`

So I gather my source from git using a script into `/home/{user}/src/{branch}/{repo}/{file}` and just want to point OpenGrok to that rather than copying to `/var/snap/opengrok/common/src`.

Now it may be that none of this is needed. I still need to go back and experiment with issue `#6` where you answered my question about ssh.

I might be able to do the `/etc/fstab` "cheat" you mention. I don't know enough about snaps yet to fully understand your "provide snap" suggestion.

**Comment by kubiko** [comment]
hi @decimal1969 
I'm sorry for the late reply, (travel and holidays...)
Your use case can work, I believe.
OpenGrok itself does not address initial source directory content creation. It does help with keeping trees in sync, somewhat, and this is mostly to provide way to reindex sub-projects during sync, while keeping other project's index accessible.

That being said, `opengrok.update-source` is helper I added, but by no means you are required to use it :)
Still, I think it might support your use case
your config for the source would look like this:
```
snap set opengrok sources='{
	"repoA-branch1": {
		"branch": "branch1",
		"name": "branch1/repoA",
		"type": "git",
		"url": "https://github.com/repoA.git"
	},
	"repoA-branch2": {
		"branch": "branch2",
		"name": "branch2/repoA",
		"type": "git",
		"url": "https://github.com/repoA.git"
	},
	"repoB-branch1": {
		"branch": "branch1",
		"name": "branch1/repoB",
		"type": "git",
		"url": "https://github.com/repoB.git"
	},
	"repoB-branch2": {
		"branch": "branch2",
		"name": "branch2/repoB",
		"type": "git",
		"url": "https://github.com/repoB.git"
	}
}'
```
key `"name"` is used when cloning a given repo, and it can be in a form of a directory structure.
top-level key. e.g. `"repoA-branch1"` is just a unique key for the entry in the list, but is not used when syncing source.

then you can run
`$ sudo opengrok.update-source`
`$ sudo opengrok.index-all`
This should give you the setup you are looking for.
You can then double-check under `/var/snap/opengrok/common/src` if it created what you wanted.

**Comment by kubiko** [comment]
@decimal1969 is this still issue or we can close it?

**Comment by decimal1969** [comment]
I'll go ahead and close. I have not gotten back around to looking at this. I found a workaround by using sudo for now.
